### PR TITLE
adding IPv6 supprt to addr messages

### PR DESCRIPTION
**Pull request by EthanHeilman**
Added IPv6 support to addr messages + sanity tests. 
I tested this code against a bitcoin node using a v4 ip address patched to accept v6 addr messages to confirm capability with bitcoind.
I also validated the hex in wireshark.

### CODE REVIEW

**Comment by petertodd** [comment]
Great!

Mind adding the code you tested it with to the examples/ directory? Doesn't have to be pretty; just want to have something using this in real life. We can always clean it up later.

**Comment by EthanHeilman** [comment]
Added my test code.

**Comment by petertodd** [comment]
Great!

Last thing is it looks like you have some tailing whitespace, as well as places where you've mixed up spaces and tabs. You'll see the latter if you run the unittests with python3. Fix that and we're good.

**Comment by EthanHeilman** [comment]
When I did a reset to fix my commit, it auto-closed this pull request and despite new commits it seems to resist my attempts to reopen it. 

I have created a new pull request here: 
https://github.com/petertodd/python-bitcoinlib/pull/50

**Pull request closed without merging**
