### PR TITLE
Add support for Dogecoin

### PR DESCRIPTION
**Pull request by rnicoll**
Adds a second optional parameter to SelectParams() and SelectCoreParams() to enable multiple coin support, and adds Dogecoin as an example.

This is currently extremely naive (for example subsidy halving interval is used differently in Dogecoin difficulty calculations), however this is enough to enable basic usage with dogecoind.

Feedback would be greatly appreciated.

### CODE REVIEW

**Comment by petertodd** [comment]
A better way to do this is to create a dogecoin-bitcoinlib fork of this library. Or create a dogecoin-bitcoinlib that depends on python-bitcoinlib, and rewrites params as needed. I'd be interested in seeing what solution works best; I suspect the latter. 

I won't be adding any altcoin support to python-bitcoinlib itself.

CC: @btcdrak

**Comment by rnicoll** [comment]
A wrapper around bitcoinlib makes sense. There's a few more complicated cases I haven't started work on yet (AuxPoW support, for example), but they should all be possible by creating extension classes I think.

**Comment by petertodd** [comment]
Sounds reasonable to me. Is your in-progress work up somewhere?

**Comment by rnicoll** [comment]
If you mean for a wrapper library; not yet, and need move other projects along for a bit, will come back to this later.

If you mean for the cross-chain stuff, https://github.com/rnicoll/cate - it's essentially enough to prove the theory, although lack of transaction replacement support in Bitcoin/Dogecoin Core means the refund transactions can block the actual payment transactions, so need to look at that.

**Comment by petertodd** [comment]
Thanks! I'll take to look at that code soon.

**Pull request closed without merging**
