### PR TITLE
Bech32 address support

### PR DESCRIPTION
**Pull request by dgpv**
Add Bech32-encoded address support

This is based on https://github.com/petertodd/python-bitcoinlib/pull/154 

Introduce CBase58Address and CBech32Address

make CBitcoinAddress a wrapper that returns CBase58Address or CBech32Address depending on input data
    
introduce to_redeemScript() method, because for P2WPKHBitcoinAddress redeem script is not the same as scriptPubKey.
    
unfortunately, for P2WSHBitcoinAddress to_redeemScript() cannot
be implemented, as we need all pubkeys for that, and not only the hash.

### CODE REVIEW

**Comment by dgpv** [comment]
oops, duplicate

**Comment by dgpv** [comment]
We plan to maintain a derivative of this library at https://github.com/Simplexum/python-bitcoindata 

We changed the name, as we will strip all bitcoin network-related code from it (bitcoin/bloom.py, bitcoin/messages.py, bitcoin/net.py)

**Comment by dgpv** [comment]
> What's stopping this from being merged?

https://github.com/petertodd/python-bitcoinlib/issues/192

**Comment by petertodd** [comment]
Frankly, haven't reviewed this super carefully, but it all looks fine.

**Pull request merged**
