### PR TITLE
Add Sphinx docs

### PR DESCRIPTION
**Pull request by welshjf**
I did this before noticing #24. Some improvements from that previous attempt:

* Factored out the project parameters that the quickstart script duplicates all over conf.py
* Provided correct information for those parameters (authors etc.)
* Mocked out the ctypes import so API doc generation doesn't break if openssl or secp256k1 is unavailable on the build host
* Don't duplicate top-level module descriptions that belong (and sometimes are) in docstrings

Things I didn't do:
* ReadTheDocs theme
* Duplicate the README contents. Probably some of it should be moved to docs, but I'd think it would help to make that decision independently of having the docs in the first place.

### CODE REVIEW

**Comment by petertodd** [comment]
Thanks! This looks good.

Mind adding a bit of meta-documentation somewhere that says how to actually build the sphinx docs?

**Comment by welshjf** [comment]
Will do. Do you prefer extra commits or squashed?

**Comment by welshjf** [comment]
Is this all good now?

One awkward thing I noticed is the guy who did the previous PR already claimed the project name on readthedocs... http://python-bitcoinlib.readthedocs.org/en/latest/index.html

**Comment by petertodd** [comment]
Yup! Sorry I forgot about this!

Hmm... have you tried sending him an email yet? It'd be good to get that transferred.

**Comment by welshjf** [comment]
Nope, figured I'd leave it between the two of you since that's how the transfer should happen. No reason to suspect anything but good intentions.

**Pull request merged**
