### PR TITLE
[examples] Add segwit example for spending a P2WPKH output

### PR DESCRIPTION
**Pull request by kanzure**
Here's an example for using P2WPKH.

### CODE REVIEW

**Comment by mcelrath** [comment]
tACK (works)

So this example has a different character than the others in that it requires a running `bitcoind -regtest` while the other `spend-*` examples do not. While I think that's okay given python-bitcoinlib's tight coupling to bitcoind, it might be a good idea to do one of:

1. Modify the other examples to use regtest
2. If regtest connection fails, use a static txid/vout like the other examples do (and print a warning)
3. Give slightly more verbose error indicating how to run regtest, which can sometimes be a PITA. Your example is nice because it works with an uninitialized regtest (don't have to generatetoaddress or addnode).
4. Try to run `bitcoind -regtest` on startup if the connect fails. Ideally, create a datadir specific to this example and use it.

My preference is for (2) or (4) over giving the user a tutorial on how to run regtest in the error messages.

**Comment by kanzure** [comment]
I can't remember ever running any of the other examples, only using them as a reference from time to time. You're correct that adding a static txid/vout and making RPC optional would make this runnable without a node, but I am not sure if that has any particular utility?

For your (4), I would suggest turning bitcoin's `test_framework` into a python library.

**Comment by mcelrath** [comment]
It has utility in as far as an inexperienced user can just run it without having to figure out regtest, ;-) and also just uniformity between the different examples.

(Though, browbeating people to learn to use regtest is itself valuable...but perhaps this is not the place for it)

**Comment by JSwambo** [comment]
ACK df646ad

**Pull request merged**
