### PR TITLE
Add getblockchaininfo and getmempoolinfo

### PR DESCRIPTION
**Pull request by spinza**
Adding some calls explicitly.

### CODE REVIEW

**Comment by petertodd** [comment]
Like the other RPC calls, these should do whatever is appropriate to convert datatypes to something more consistant with other parts of the RPC api.

**Comment by spinza** [comment]
OK will do.

**Comment by dbolser** [comment]
We've got a similar patch locally. Is this suitable to merge? Can you add some tests?

Many thanks,
Dan.

**Comment by SachinMeier** [comment]
I just opened #242 which adds these two calls as well as all other new calls as of v0.19.0.1. Hope it helps!

**Comment by Godstimendako** [comment]
https://github.com/petertodd/python-bitcoinlib

**Comment by Godstimendako** [comment]
https://github.com/petertodd/python-bitcoinlib

**Comment by Godstimendako** [comment]
https://github.com/petertodd/python-bitcoinlib

**Pull request closed without merging**
