### PR TITLE
Add TravisCI, Docs, and use Markdown for the README

### PR DESCRIPTION
**Pull request by icook**
I wanted to split this up a bit more cleanly, but they were too intertwined/dependent as to make it a real PITA. Let me know if you'd like me to clean something up a bit.

### CODE REVIEW

**Comment by rubensayshi** [comment]
@icook could you do the rebase, would be really nice to have this in, or if yo don't have time to do so, let me know and I'll do it and create a new PR ;-)

**Comment by petertodd** [comment]
@icook 

Hey, so we finally got spinx docs via pull-req #68 

As per https://github.com/petertodd/python-bitcoinlib/pull/68#issuecomment-113789760 it'd be good to get these new docs on readthedocs.org - what's the best way to accomplish this?

**Comment by rubensayshi** [comment]
@petertodd what about travis?

**Comment by petertodd** [comment]
@rubensayshi Oh, good point!

If anyone wants to re-open that part as another pull-req, go right ahead!

**Pull request closed without merging**
